name = "QuadraticInterpolationMethod"
uuid = "e7241e48-3d3b-4ed3-9130-818aaeb8a636"
authors = ["hyrodium <hyrodium@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
